name: douban_movie_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: 4.0.3
  date_format: ^1.0.8
  # 国际化
  intl: ^0.16.0

  dio: ^3.0.1
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  shared_preferences: ^0.5.3+5
  # 本地json对象存储
  localstorage: ^2.0.0

  # UI
  oktoast: ^2.3.1
  pull_to_refresh: ^1.5.6

  path_provider: ^1.1.0

  # 谁用谁闪亮
  shimmer: ^1.0.0

  cached_network_image: ^2.0.0-rc.1

  carousel_slider: ^1.1.0
  flutter_swiper: ^1.1.4
  palette_generator: ^0.2.0
  #图片保存到本地相册
  image_gallery_saver: ^1.2.2
  #权限申请
  permission_handler: ^5.0.0+hotfix.3

  sticky_headers: "^0.1.8"
  flutter_sticky_header: "^0.4.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 国际化
  intl_translation: ^0.17.2


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true